name: Update gist with latest YouTube videos
on:
  schedule:
    - cron: "1 */7 * * *"
  
jobs:
  update-gist:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@master

      - name: "Setup Python"
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: "Pip install"
        run: pip install -r requirements.txt

      - name: "Update gist"
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GIST_ID: e61df13cc190ae268d6295db2edc36ab
          CHANNEL_ID: UC9a0uk9XDEWfYKGpC0Tio7A
          YT_API_KEY: ${{ secrets.YT_API_KEY }}
        run: python main.py
